### ISSUE TITLE
Hello Thank you for sharing, why can't I open your project with KiCad5.14?

### ISSUE THREAD

**Issue by QABQ** [mpater/bldc-BMS#1]
Hello Thank you for sharing, why can't I open your project with KiCad5.14?

**Comment by mpater** [comment]
Hello. Are you having any specific errors?
I believe KiCad should be able to detect and open/import/convert a KiCad 4 to KiCad 5 project. I'll update and push the changes in a couple of days.

**Comment by SecturityException** [comment]
> Hello. Are you having any specific errors?
> I believe KiCad should be able to detect and open/import/convert a KiCad 4 to KiCad 5 project. I'll update and push the changes in a couple of days.

**Comment by QABQ** [comment]
I can only open "bldc-BMS.sch" but cannot open other schematics

**Comment by mpater** [comment]
Pushed updates, lots of content updated. Has been saved in 5.1.4 as well. Give it another go.

**Comment by QABQ** [comment]
I will try again, thank you for your help.
